services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: fuji
      POSTGRES_PASSWORD: fuji123
      POSTGRES_DB: fujitravel
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
