// Russian → Latin transliteration per ICAO Doc 9303.
// Mirrors backend/internal/translit/icao.go so that the client-side
// autogenerated name_lat matches what the backend would produce.
const ICAO = {
  'А': 'A', 'Б': 'B', 'В': 'V', 'Г': 'G', 'Д': 'D', 'Е': 'E', 'Ё': 'E',
  'Ж': 'ZH', 'З': 'Z', 'И': 'I', 'Й': 'I', 'К': 'K', 'Л': 'L', 'М': 'M',
  'Н': 'N', 'О': 'O', 'П': 'P', 'Р': 'R', 'С': 'S', 'Т': 'T', 'У': 'U',
  'Ф': 'F', 'Х': 'KH', 'Ц': 'TC', 'Ч': 'CH', 'Ш': 'SH', 'Щ': 'SHCH',
  'Ъ': 'IE', 'Ы': 'Y', 'Ь': '', 'Э': 'E', 'Ю': 'IU', 'Я': 'IA',
};

export function ruToLatICAO(s) {
  if (!s) return '';
  const upper = s.toUpperCase();
  let out = '';
  for (const ch of upper) {
    if (ICAO[ch] !== undefined) out += ICAO[ch];
    else if (/[A-Z0-9\s\-.,]/.test(ch)) out += ch;
  }
  return out;
}
